### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by Obstruite** [mechakotik/tails-adventure#1]
Hi! Great job remaking this old and obscure game. You've made some great quality of life improvements. Unfortunately, I find myself stuck early on as I am unable to change inventory at Tails' house: each time I try to replace items with others or even switch placements, the inventory is back to what it was in the next level I go to or when I visit the house again. Have you by any chance received similar reports? Do you have an idea on how to correct it within the game files in a simple way? Thank you.

**Comment by mechakotik** [comment]
Hi, thanks for the report! It is surprising how no one reported this bug through ~2000 downloads. This commit should fix the problem: 818430e. I'll build the new version for Windows soon.
