### ISSUE TITLE
Bounce pad bug

### ISSUE THREAD

**Issue by Obstruite** [mechakotik/tails-adventure#2]
Hi. Thank you for being so quick to reply to my force issue and upload a new build. I just tried it to check if the inventory save was fixed, but I couldn't get far in the first level, as the first jump pad you find in the game suddenly doesn't take you higher than a normal jump. See in the following link: https://streamable.com/wgkg80. Hopefully this is the last major bug you will have to deal with...

**Comment by mechakotik** [comment]
Hi again. Seems like I've accidentally broken it while coding water physics in Cavern Island. 352f676 should fix the problem. TA_Character code architecture is so bad, but it's too late to rewrite it from the ground up...
