### ISSUE TITLE
Playable status?

### ISSUE THREAD

**Issue by diegopau** [mechakotik/tails-adventure#3]
Hi! sorry for opening an issue for this sort of question. I didn't find other way to contact you. I just wanted to know:  is it the game playable from beginning to end even if it is a "Demo" for now? or should I wait until further releases?

Thank you for your work on this.

**Comment by mechakotik** [comment]
No, current demo contains only the first 3 levels: Poloy Forest, Volcanic Tunnel and Polly Mt. 1. Just noticed this wasn't stated in README, thanks!

**Comment by diegopau** [comment]
Good to know! I will wait patiently then :) thanks for the quick reply!
