### ISSUE TITLE
CTD on latest Windows build

### ISSUE THREAD

**Issue by AmaliaKalio** [mechakotik/tails-adventure#4]
OS: Win 11 Pro

Nothing in event viewer, unfortunately. Also no error spat out when run via cmd.

**Comment by mechakotik** [comment]
What's an exit code? `echo %errorlevel%` after running from cmd.

Do you have latest [Visual C++ redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) installed?

**Comment by AmaliaKalio** [comment]
It's installed. Exit code is 9009.

**Comment by mechakotik** [comment]
Looks like it's some dependent DLL that presents on my system but not on yours. Unfortunately, it does not say what exactly is missing. I'll look into it when I'll be back home.

Maybe you didn't install graphics drivers properly? Do you have vulkan-1.dll on your system?

**Comment by AmaliaKalio** [comment]
I do, under sys32.

**Comment by diegopau** [comment]
I just tried too and it crashes for me. However if I run `echo %errorlevel%` right after running from cmd I get a 0

**Comment by mechakotik** [comment]
Unless I'm able to reproduce it, you may try building from source (see tutorial in README) and running game executable from MSYS shell. If it works fine here but not when running from Windows, copy all the DLLs from `[MSYS install folder]/mingw/bin`, then try deleting DLLs one by one and launching game from Windows to see which were missing. This may sound strange but I don't know other way to debug it if it doesn't say what's missing.

**Comment by diegopau** [comment]
In my case after building the from source the behavior is the same. It silently crashes. I am using Windows 10 Pro 22H2 with the latest updates.

When following the steps this command:
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-git
gave an error:
error: target not found: mingw-w64-x86_64-git
-bash: git: command not found

But it was easy to fix by doing:
pacman -S git
everything else worked smoothly

**Comment by AmaliaKalio** [comment]
After building, I'm getting different results based on if I load it in powershell, or cmd. Both now exit with errorcode 0.

PS:
```
Save file assets/default_config was not found, skipping
Save file config was not found, skipping
Unknown parameter vsync

```
CMD:
```
Save file config was not found, skipping
assets/sound/title.vgm load failed
Failed loading gme.dll: The specified module could not be found.
```

**Comment by AmaliaKalio** [comment]
It appears that it's attempting to use absolute paths (out of where specifically, I don't know) rather than relative on the Windows build. To test, I modified filesystem.cpp to add the executable folder path to the start of the assets folder (below). This seemed to clear the error of finding `default_config`, but it should be noted that this isn't a perfect solution as the same operation needs to _also_ be done when finding the save file location in save.cpp. It also seems that `config` as opposed to `default_config` is what it's currently trying to use as the game's save file, so that should probably be revisited.

```c++
#include <windows.h>
#include <iostream>
std::string GetExeFileName()
{
    char buffer[MAX_PATH];
    GetModuleFileName(NULL, buffer, MAX_PATH);
    return std::string(buffer);
}
std::string GetExePath()
{
    std::string f = GetExeFileName();
    return f.substr(0, f.find_last_of("\\/"));
}
const std::string TA::filesystem::getAssetsPath()
{
    #ifdef __ANDROID__
        return ".";
    #else
        #ifdef TA_LINUX_INSTALL
            return "/usr/share/tails-adventure";
        #else
            return GetExePath()+"/assets";
        #endif
    #endif
}
```

Something else odd that I noticed, was that building `tails-adventure` seems to drop an exe file into `.\tails-adventure\build\Release`, as expected, but that's it. All of the other assets seemed to get built into `.\tails-adventure-build\output\` just fine, though.

**Comment by mechakotik** [comment]
Thanks for pointing out to the executable path problem, however it only appears when running from terminal while being in another directory.

The reason it crashes on startup is libgme not linking statically and missing when trying to launch. However, on Linux it links statically fine with the same settings. You may try enabling libgme static linking explicitly by adding this:

```cmake
set(SDL2MIXER_GME_SHARED OFF)
```
to CMakeLists.txt near other SDL2MIXER options. Sorry, I can't test it myself right now.

Regarding output directory, running `cmake --install .` would copy executable and assets in `build/output` directory.

**Comment by mechakotik** [comment]
I have fixed CMakeLists to link libgme statically and updated Windows binary release, should work fine now.

**Comment by diegopau** [comment]
It works for me now. Great demo by the way!
